/*
 * Register Map.h
 *
 *  Created on: Feb 9, 2020
 *      Author: seif_
 */

#ifndef REGISTER_MAP_H_
#define REGISTER_MAP_H_

#include "utils.h"
#include "std_types.h"

/***              GPIOADCCTL                 ***/

#define SYSCTRL_BASE 0x400FE000

#define GPIO_PORTAP 0x40004000
#define GPIO_PORTAH 0x40058000
#define GPIO_PORTBP 0x40005000
#define GPIO_PORTBH 0x40059000
#define GPIO_PORTCP 0x40006000
#define GPIO_PORTCH 0x4005A000
#define GPIO_PORTDP 0x40007000
#define GPIO_PORTDH 0x4005B000
#define GPIO_PORTEP 0x40024000
#define GPIO_PORTEH 0x4005C000
#define GPIO_PORTFP 0x40025000
#define GPIO_PORTFH 0x4005D000

#define GPIODIR     0x400
#define GPIOAFSEL   0x420
#define GPIOPCTL    0x52C
#define GPIOADCCTL  0x530
#define GPIODMACTL  0x534
#define GPIODR2R    0x500
#define GPIODR4R    0x504
#define GPIODR8R    0x508
#define GPIOPUR     0x510
#define GPIOPDR     0x514
#define GPIOODR     0x50C
#define GPIODEN     0x51C


#define RCGCGPIO OFFSET(SYSCTRL_BASE, 0x608)
#define SYSCTRL_RCC OFFSET(SYSCTRL_BASE, 0x060)
#define SYSCTRL_RCC2 OFFSET(SYSCTRL_BASE, 0x070)
#define GPIOHBCTL OFFSET(SYSCTRL_BASE, 0x06C)


/***              GPIODIR                ***/

#define GPIODIR_AP OFFSET(GPIO_PORTAP, GPIODIR)
#define GPIODIR_AH OFFSET(GPIO_PORTAH, GPIODIR)
#define GPIODIR_BP OFFSET(GPIO_PORTBP, GPIODIR)
#define GPIODIR_BH OFFSET(GPIO_PORTBH, GPIODIR)
#define GPIODIR_CP OFFSET(GPIO_PORTCP, GPIODIR)
#define GPIODIR_CH OFFSET(GPIO_PORTCH, GPIODIR)
#define GPIODIR_DP OFFSET(GPIO_PORTDP, GPIODIR)
#define GPIODIR_DH OFFSET(GPIO_PORTDH, GPIODIR)
#define GPIODIR_EP OFFSET(GPIO_PORTEP, GPIODIR)
#define GPIODIR_EH OFFSET(GPIO_PORTEH, GPIODIR)
#define GPIODIR_FP OFFSET(GPIO_PORTFP, GPIODIR)
#define GPIODIR_FH OFFSET(GPIO_PORTFH, GPIODIR)


/***              GPIOAFSEL                ***/

#define GPIOAFSEL_AP OFFSET(GPIO_PORTAP, GPIOAFSEL)
#define GPIOAFSEL_AH OFFSET(GPIO_PORTAH, GPIOAFSEL)
#define GPIOAFSEL_BP OFFSET(GPIO_PORTBP, GPIOAFSEL)
#define GPIOAFSEL_BH OFFSET(GPIO_PORTBH, GPIOAFSEL)
#define GPIOAFSEL_CP OFFSET(GPIO_PORTCP, GPIOAFSEL)
#define GPIOAFSEL_CH OFFSET(GPIO_PORTCH, GPIOAFSEL)
#define GPIOAFSEL_DP OFFSET(GPIO_PORTDP, GPIOAFSEL)
#define GPIOAFSEL_DH OFFSET(GPIO_PORTDH, GPIOAFSEL)
#define GPIOAFSEL_EP OFFSET(GPIO_PORTEP, GPIOAFSEL)
#define GPIOAFSEL_EH OFFSET(GPIO_PORTEH, GPIOAFSEL)
#define GPIOAFSEL_FP OFFSET(GPIO_PORTFP, GPIOAFSEL)
#define GPIOAFSEL_FH OFFSET(GPIO_PORTFH, GPIOAFSEL)


/***              GPIOPCTL                 ***/

#define GPIOPCTL_AP OFFSET(GPIO_PORTAP, GPIOPCTL)
#define GPIOPCTL_AH OFFSET(GPIO_PORTAH, GPIOPCTL)
#define GPIOPCTL_BP OFFSET(GPIO_PORTBP, GPIOPCTL)
#define GPIOPCTL_BH OFFSET(GPIO_PORTBH, GPIOPCTL)
#define GPIOPCTL_CP OFFSET(GPIO_PORTCP, GPIOPCTL)
#define GPIOPCTL_CH OFFSET(GPIO_PORTCH, GPIOPCTL)
#define GPIOPCTL_DP OFFSET(GPIO_PORTDP, GPIOPCTL)
#define GPIOPCTL_DH OFFSET(GPIO_PORTDH, GPIOPCTL)
#define GPIOPCTL_EP OFFSET(GPIO_PORTEP, GPIOPCTL)
#define GPIOPCTL_EH OFFSET(GPIO_PORTEH, GPIOPCTL)
#define GPIOPCTL_FP OFFSET(GPIO_PORTFP, GPIOPCTL)
#define GPIOPCTL_FH OFFSET(GPIO_PORTFH, GPIOPCTL)


/***              GPIOADCCTL                 ***/

#define GPIOADCCTL_AP OFFSET(GPIO_PORTAP, GPIOADCCTL)
#define GPIOADCCTL_AH OFFSET(GPIO_PORTAH, GPIOADCCTL)
#define GPIOADCCTL_BP OFFSET(GPIO_PORTBP, GPIOADCCTL)
#define GPIOADCCTL_BH OFFSET(GPIO_PORTBH, GPIOADCCTL)
#define GPIOADCCTL_CP OFFSET(GPIO_PORTCP, GPIOADCCTL)
#define GPIOADCCTL_CH OFFSET(GPIO_PORTCH, GPIOADCCTL)
#define GPIOADCCTL_DP OFFSET(GPIO_PORTDP, GPIOADCCTL)
#define GPIOADCCTL_DH OFFSET(GPIO_PORTDH, GPIOADCCTL)
#define GPIOADCCTL_EP OFFSET(GPIO_PORTEP, GPIOADCCTL)
#define GPIOADCCTL_EH OFFSET(GPIO_PORTEH, GPIOADCCTL)
#define GPIOADCCTL_FP OFFSET(GPIO_PORTFP, GPIOADCCTL)
#define GPIOADCCTL_FH OFFSET(GPIO_PORTFH, GPIOADCCTL)


/***              GPIODMACTL                  ***/

#define GPIODMACTL_AP OFFSET(GPIO_PORTAP, GPIODMACTL)
#define GPIODMACTL_AH OFFSET(GPIO_PORTAH, GPIODMACTL)
#define GPIODMACTL_BP OFFSET(GPIO_PORTBP, GPIODMACTL)
#define GPIODMACTL_BH OFFSET(GPIO_PORTBH, GPIODMACTL)
#define GPIODMACTL_CP OFFSET(GPIO_PORTCP, GPIODMACTL)
#define GPIODMACTL_CH OFFSET(GPIO_PORTCH, GPIODMACTL)
#define GPIODMACTL_DP OFFSET(GPIO_PORTDP, GPIODMACTL)
#define GPIODMACTL_DH OFFSET(GPIO_PORTDH, GPIODMACTL)
#define GPIODMACTL_EP OFFSET(GPIO_PORTEP, GPIODMACTL)
#define GPIODMACTL_EH OFFSET(GPIO_PORTEH, GPIODMACTL)
#define GPIODMACTL_FP OFFSET(GPIO_PORTFP, GPIODMACTL)
#define GPIODMACTL_FH OFFSET(GPIO_PORTFH, GPIODMACTL)


/***              GPIODR2R                  ***/

#define GPIODR2R_AP OFFSET(GPIO_PORTAP, GPIODR2R)
#define GPIODR2R_BP OFFSET(GPIO_PORTBP, GPIODR2R)
#define GPIODR2R_CP OFFSET(GPIO_PORTCP, GPIODR2R)
#define GPIODR2R_DP OFFSET(GPIO_PORTDP, GPIODR2R)
#define GPIODR2R_EP OFFSET(GPIO_PORTEP, GPIODR2R)
#define GPIODR2R_FP OFFSET(GPIO_PORTFP, GPIODR2R)
#define GPIODR2R_AH OFFSET(GPIO_PORTAH, GPIODR2R)
#define GPIODR2R_BH OFFSET(GPIO_PORTBH, GPIODR2R)
#define GPIODR2R_CH OFFSET(GPIO_PORTCH, GPIODR2R)
#define GPIODR2R_DH OFFSET(GPIO_PORTDH, GPIODR2R)
#define GPIODR2R_EH OFFSET(GPIO_PORTEH, GPIODR2R)
#define GPIODR2R_FH OFFSET(GPIO_PORTFH, GPIODR2R)


/***              GPIODR4R                  ***/

#define GPIODR4R_AP OFFSET(GPIO_PORTAP, GPIODR4R)
#define GPIODR4R_BP OFFSET(GPIO_PORTBP, GPIODR4R)
#define GPIODR4R_CP OFFSET(GPIO_PORTCP, GPIODR4R)
#define GPIODR4R_DP OFFSET(GPIO_PORTDP, GPIODR4R)
#define GPIODR4R_EP OFFSET(GPIO_PORTEP, GPIODR4R)
#define GPIODR4R_FP OFFSET(GPIO_PORTFP, GPIODR4R)
#define GPIODR4R_AH OFFSET(GPIO_PORTAH, GPIODR4R)
#define GPIODR4R_BH OFFSET(GPIO_PORTBH, GPIODR4R)
#define GPIODR4R_CH OFFSET(GPIO_PORTCH, GPIODR4R)
#define GPIODR4R_DH OFFSET(GPIO_PORTDH, GPIODR4R)
#define GPIODR4R_EH OFFSET(GPIO_PORTEH, GPIODR4R)
#define GPIODR4R_FH OFFSET(GPIO_PORTFH, GPIODR4R)


/***              GPIODR8R                 ***/

#define GPIODR8R_AP OFFSET(GPIO_PORTAP, GPIODR8R)
#define GPIODR8R_BP OFFSET(GPIO_PORTBP, GPIODR8R)
#define GPIODR8R_CP OFFSET(GPIO_PORTCP, GPIODR8R)
#define GPIODR8R_DP OFFSET(GPIO_PORTDP, GPIODR8R)
#define GPIODR8R_EP OFFSET(GPIO_PORTEP, GPIODR8R)
#define GPIODR8R_FP OFFSET(GPIO_PORTFP, GPIODR8R)
#define GPIODR8R_AH OFFSET(GPIO_PORTAH, GPIODR8R)
#define GPIODR8R_BH OFFSET(GPIO_PORTBH, GPIODR8R)
#define GPIODR8R_CH OFFSET(GPIO_PORTCH, GPIODR8R)
#define GPIODR8R_DH OFFSET(GPIO_PORTDH, GPIODR8R)
#define GPIODR8R_EH OFFSET(GPIO_PORTEH, GPIODR8R)
#define GPIODR8R_FH OFFSET(GPIO_PORTFH, GPIODR8R)


/***              GPIOPUR                  ***/

#define GPIOPUR_AP OFFSET(GPIO_PORTAP, GPIOPUR)
#define GPIOPUR_BP OFFSET(GPIO_PORTBP, GPIOPUR)
#define GPIOPUR_CP OFFSET(GPIO_PORTCP, GPIOPUR)
#define GPIOPUR_DP OFFSET(GPIO_PORTDP, GPIOPUR)
#define GPIOPUR_EP OFFSET(GPIO_PORTEP, GPIOPUR)
#define GPIOPUR_FP OFFSET(GPIO_PORTFP, GPIOPUR)
#define GPIOPUR_AH OFFSET(GPIO_PORTAH, GPIOPUR)
#define GPIOPUR_BH OFFSET(GPIO_PORTBH, GPIOPUR)
#define GPIOPUR_CH OFFSET(GPIO_PORTCH, GPIOPUR)
#define GPIOPUR_DH OFFSET(GPIO_PORTDH, GPIOPUR)
#define GPIOPUR_EH OFFSET(GPIO_PORTEH, GPIOPUR)
#define GPIOPUR_FH OFFSET(GPIO_PORTFH, GPIOPUR)


/***              GPIOPDR                  ***/


#define GPIOPDR_AP OFFSET(GPIO_PORTAP, GPIOPDR)
#define GPIOPDR_BP OFFSET(GPIO_PORTBP, GPIOPDR)
#define GPIOPDR_CP OFFSET(GPIO_PORTCP, GPIOPDR)
#define GPIOPDR_DP OFFSET(GPIO_PORTDP, GPIOPDR)
#define GPIOPDR_EP OFFSET(GPIO_PORTEP, GPIOPDR)
#define GPIOPDR_FP OFFSET(GPIO_PORTFP, GPIOPDR)
#define GPIOPDR_AH OFFSET(GPIO_PORTAH, GPIOPDR)
#define GPIOPDR_BH OFFSET(GPIO_PORTBH, GPIOPDR)
#define GPIOPDR_CH OFFSET(GPIO_PORTCH, GPIOPDR)
#define GPIOPDR_DH OFFSET(GPIO_PORTDH, GPIOPDR)
#define GPIOPDR_EH OFFSET(GPIO_PORTEH, GPIOPDR)
#define GPIOPDR_FH OFFSET(GPIO_PORTFH, GPIOPDR)


/***              GPIOODR                  ***/

#define GPIOODR_AP OFFSET(GPIO_PORTAP, GPIOODR)
#define GPIOODR_BP OFFSET(GPIO_PORTBP, GPIOODR)
#define GPIOODR_CP OFFSET(GPIO_PORTCP, GPIOODR)
#define GPIOODR_DP OFFSET(GPIO_PORTDP, GPIOODR)
#define GPIOODR_EP OFFSET(GPIO_PORTEP, GPIOODR)
#define GPIOODR_FP OFFSET(GPIO_PORTFP, GPIOODR)
#define GPIOODR_AH OFFSET(GPIO_PORTAH, GPIOODR)
#define GPIOODR_BH OFFSET(GPIO_PORTBH, GPIOODR)
#define GPIOODR_CH OFFSET(GPIO_PORTCH, GPIOODR)
#define GPIOODR_DH OFFSET(GPIO_PORTDH, GPIOODR)
#define GPIOODR_EH OFFSET(GPIO_PORTEH, GPIOODR)
#define GPIOODR_FH OFFSET(GPIO_PORTFH, GPIOODR)


/***              GPIODEN                  ***/

#define GPIODEN_AP OFFSET(GPIO_PORTAP, GPIODEN)
#define GPIODEN_BP OFFSET(GPIO_PORTBP, GPIODEN)
#define GPIODEN_CP OFFSET(GPIO_PORTCP, GPIODEN)
#define GPIODEN_DP OFFSET(GPIO_PORTDP, GPIODEN)
#define GPIODEN_EP OFFSET(GPIO_PORTEP, GPIODEN)
#define GPIODEN_FP OFFSET(GPIO_PORTFP, GPIODEN)
#define GPIODEN_AH OFFSET(GPIO_PORTAH, GPIODEN)
#define GPIODEN_BH OFFSET(GPIO_PORTBH, GPIODEN)
#define GPIODEN_CH OFFSET(GPIO_PORTCH, GPIODEN)
#define GPIODEN_DH OFFSET(GPIO_PORTDH, GPIODEN)
#define GPIODEN_EH OFFSET(GPIO_PORTEH, GPIODEN)
#define GPIODEN_FH OFFSET(GPIO_PORTFH, GPIODEN)

/**/
#define GPIODATA_AP OFFSET(GPIO_PORTAP, 0x3FC)
#define GPIODATA_BP OFFSET(GPIO_PORTBP, 0x3FC)
#define GPIODATA_CP OFFSET(GPIO_PORTCP, 0x3FC)
#define GPIODATA_DP OFFSET(GPIO_PORTDP, 0x3FC)
#define GPIODATA_EP OFFSET(GPIO_PORTEP, 0x3FC)
#define GPIODATA_FP OFFSET(GPIO_PORTFP, 0x3FC)
#define GPIODATA_AH OFFSET(GPIO_PORTAH, 0x3FC)
#define GPIODATA_BH OFFSET(GPIO_PORTBH, 0x3FC)
#define GPIODATA_CH OFFSET(GPIO_PORTCH, 0x3FC)
#define GPIODATA_DH OFFSET(GPIO_PORTDH, 0x3FC)
#define GPIODATA_EH OFFSET(GPIO_PORTEH, 0x3FC)
#define GPIODATA_FH OFFSET(GPIO_PORTFH, 0x3FC)
/**/


/** RCC PINS **/
#define PWRDN 13
#define BYBASS 11
#define USESYSDIV 22


#endif
